# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SORSE
logo: "/assets/images/logo.png"
og_image: "/assets/images/logo.png"
baseurl: ""  # for testing, also check .circleci/circle_urls.sh
url: &url "https://sorse.github.io"
repository: SORSE/sorse.github.io
email: &email SORSE.enquiries@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  SORSE: Series of Online Research Software Events 2020
twitter_username: &twitter Int_SORSE
github_username: &github SORSE
minimal_mistakes_skin: default
search: true
future: true
indico_base_event: https://indico.scc.kit.edu/event/863

twitter:
  username: *twitter

github:
  username: *github

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
excerpt_length: 100

include:
  - _pages

# Exclude these files from production site
exclude:
  - scripts
  - _site
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - LICENSE

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "SORSE"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Series of Online Research Software Events"
  github: *github
  twitter: *twitter
  email: *email
  website: *url

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _bazaar
  - scope:
      path: ""
      type: bazaar
    values:
      layout: topic
      author_profile: true
      share: true
      collection_button:
        name: Other topics
        url: /programme/bazaar/#topics
      sidebar:
        nav: bazaar
  # _faq
  - scope:
      path: ""
      type: faq
    values:
      layout: single
      author_profile: false
      share: false
      collection_button:
        name: FAQ
        url: /faq/
      sidebar:
        nav: faq
  - scope:
      path: ""
      type: programme_teams
    values:
      sidebar:
        nav: "programme"
      toc: true
      toc_sticky: true
      layout: programme-team

collections:
  bazaar:
    output: true
    permalink: /programme/bazaar/:path/
  faq:
    output: true
    permalink: /:collection/:path
  programme_teams:
    output: true
    permalink: /programme/:path/
